import sys
import os
import numpy as np
import argparse
import yaml
import emcee
import pandas as pd
import time
from schwimmbad import MPIPool
from scipy.interpolate import interp1d

# Add paths to access your local modules for the DM mass calculation
sys.path.append('/home/rana/github_0/gammat_scatter/src/')
from halopy import halo

# Internal imports
from model import model
from colossus.cosmology import cosmology
from colossus.halo import concentration

# Set Cosmology
params = {'flat': True, 'H0': 100, 'Om0': 0.319, 'Ob0': 0.049, 'sigma8': 0.813, 'ns': 0.96}
cosmology.addCosmology('myCosmo', **params)
cosmo = cosmology.setCosmology('myCosmo')

def build_paths(args, config, oversamp):
    """
    Reconstructs the EXACT output directory generated by the MPI script
    using the logic pulled from collate.py.
    """
    dir_name = '%2.2f_%2.2f_seed_%d_ovp_%d' % (
        args.logMmin, args.logMmax, config['seed'], int(oversamp)
    )
    
    if args.sigma_Roff != -999:
        dir_name += '_sigma_off_%2.2f' % (args.sigma_Roff)
    if args.sigma_logre > 0.0:
        dir_name += '_sigRe_%2.2f' % (args.sigma_logre)
        
    outdir = os.path.join(config.get("mockdir", "./output/"), dir_name) + "/"
    return outdir

def lnprior(x, model_type):
    """
    Evaluates prior based on the specific model type.
    """
    if model_type == 'nfw_fixed':
        alpha, logmh = x
        if 0.1 < alpha < 5 and 9 < logmh < 16: return 0.0 
    
    elif model_type == 'nfw_free':
        alpha, logmh, conc = x
        if 0.1 < alpha < 5 and 9 < logmh < 16 and 0.1 < conc < 20: return 0.0 
    
    return -np.inf

def lnprob(x, rbins, data, icov, mm, median_lzred, model_type, Re_Mpc):
    lp = lnprior(x, model_type)
    if not np.isfinite(lp):
        # +2 because we append [chisq, f_star_5Re]
        return -np.inf, 5 * np.ones(len(data) + 2)
    
    # Unpack parameters into the standardized [alpha, logmh, conc, beta] for set_esd_spl
    if model_type == 'nfw_fixed':
        c = concentration.concentration(10**x[1], '200m', median_lzred, model='diemer19')
        x_model = np.array([x[0], x[1], c])
    
    elif model_type == 'nfw_free':
        x[0] = 1.0
        x_model = np.array([x[0], x[1], x[2]])
   
    begin   =   time.time()
    # 1. Model prediction for chi-squared
    _, esd = mm.set_esd_spl(x_model, rbins, lzred=median_lzred)
    Delta = esd - data
    chisq = np.dot(Delta, np.dot(icov, Delta))
    
    print('Parameters and chisq')
    print(x_model, chisq)

    if chisq < 0 or np.isnan(chisq):
        return -np.inf, 5 * np.ones(len(data) + 2)
        
    # 2. Compute the stellar fraction within 5*Re
    try:
        R_eval = 5.0 * Re_Mpc
        R_eval_pc = R_eval 
        
        # Stellar properties at 5 Re (alpha * normalized spline)
        sigma_s = x_model[0] * 10**(mm.spl_log_sigma_s(np.log10(R_eval)))
        esd_s = x_model[0] * 10**(mm.spl_log_esd_s(np.log10(R_eval)))
        M_star = np.pi * (R_eval_pc**2) * (sigma_s + esd_s)
        
        # Dark Matter properties at 5 Re (Using halopy)
        # Passing R_eval as an array to ensure halopy returns an array we can index
        hp = halo(log_mtot=x_model[1], con_par=x_model[2], omg_m=mm.Om0, beta=x_model[3])
        sigma_dm = hp.sigma_gnfw(r=np.array([R_eval]))[0]
        esd_dm = hp.esd_gnfw(r=np.array([R_eval]))[0]
        M_dm = np.pi * (R_eval_pc**2) * (sigma_dm + esd_dm)
        
        # Fraction of stellar mass to total mass within 5 Re
        f_star_5Re = M_star / (M_star + M_dm)
    except Exception as e:
        f_star_5Re = np.nan
    
    print('single evaluation time:', time.time() - begin)
    # Append both chisq and the computed stellar fraction to the blob
    blob = np.append(esd, [f_star_5Re, chisq])
    return lp - chisq * 0.5, blob

def runchain(Ntotal, sampler, chainf, blobf, pos, nwalkers):
    blnk = [""]
    with open(chainf, "w") as fchain, open(blobf, "w") as fblob:
        iterno = 1
        for result in sampler.sample(pos, iterations=Ntotal, store=1):
            posn, probn, staten, blobsn = result
            for i in range(nwalkers):
                np.savetxt(fchain, posn[i], newline=' ')
                np.savetxt(fchain, [sampler.acceptance_fraction[i], -2.*probn[i]], newline=' ')
                np.savetxt(fblob, blobsn[i], newline=' ')
                np.savetxt(fchain, blnk, fmt='%s')
                np.savetxt(fblob, blnk, fmt='%s')
            if iterno % 100 == 0:
                print(f"Iteration number: {iterno} of {Ntotal} done")
            iterno += 1
            posnew = result[0]
    return posnew

if __name__ == "__main__":
    pool = MPIPool()
    if not pool.is_master():
        pool.wait()
        sys.exit(0)                 

    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--config", help="Configuration file", required=True)
    parser.add_argument("--mockdir", help="mock esd directory", required=True)
    parser.add_argument("--model_type", help="Type of model to run", 
                        choices=['nfw_fixed', 'nfw_free', 'gnfw_fixed', 'gnfw_free'], required=True)
    parser.add_argument("--logMmin", help="minimum stellar mass", type=float, required=True)
    parser.add_argument("--logMmax", help="maximum stellar mass", type=float, required=True)
    parser.add_argument("--seed", help="seed", default=123, type=int)
    parser.add_argument("--Rpmin", help="min projected radius in units of half-light radius", default=3.0, type=float)
    
    # Flags required to mirror the collate pathing (Covariance oversampling removed)
    parser.add_argument("--oversamp_sig", help="Oversampling fraction for Signal", type=float, default=100.0)
    parser.add_argument("--sigma_Roff", help="miscentering sigma for the rayleigh dist", type=float, default=-999)
    parser.add_argument("--sigma_logre", help="Gaussian scatter applied to llogre", type=float, default=0.0)

    args = parser.parse_args()

    with open(args.config, 'r') as ymlfile:
        config = yaml.safe_load(ymlfile)
    
    # Sync seed
    config['seed'] = int(args.seed)
    config['mockdir'] = args.mockdir

    # Cosmology & Model Params
    H0 = config['H0'] 
    Om0 = config['Om0'] 
    lenstype = config['lenstype']     
    zlmin = config['zlmin'] 
    zlmax = config['zlmax'] 
    Njacks = config['Njacks'] 
    zdiff = config['zdiff'] 

    # 1. Build Exact Paths dynamically using collate logic (Only need Signal now)
    outdir_sig = build_paths(args, config, args.oversamp_sig)
    out_base = f'lmstelmin_{args.logMmin:2.2f}_lmstelmax_{args.logMmax:2.2f}'
    sig_file = os.path.join(outdir_sig, f'dsigma.dat_{out_base}')

    print(f"--- Starting MCMC: {args.model_type} | [{args.logMmin} - {args.logMmax}] ---")
    print(f"Reading Signal: {sig_file}")

    # Load Data and build diagonal covariance directly from the error column
    rbins, data, err, xdata, xerr, stelesd, invsigc, invsigcsq = np.loadtxt(sig_file, unpack=True)
    cov = np.diag(err**2)

    # Fix minimum projected separation based on metadata
    lens_metadata = pd.read_csv(f'/net/dobbe/data2/github/gammat_scatter/lens_sample_{zlmin:2.1f}_{zlmax:2.1f}.dat', delim_whitespace=1)
    idx_lens = (lens_metadata['logMmin'] == args.logMmin) & (lens_metadata['logMmax'] == args.logMmax)
    
    # Calculate Re_Mpc for the mask and the stellar fraction calculation
    Re_Mpc = lens_metadata['re_50'][idx_lens].values[0] / 1e3 # Convert kpc to Mpc
    Rmin = Re_Mpc * args.Rpmin 
    
    idx_mask = (rbins < 0.1) & (rbins > Rmin)
    rbins = rbins[idx_mask]
    data = data[idx_mask]
    cov = cov[idx_mask][:, idx_mask]
    
    # Precompute and Z-distribution
    fpath = f'./precompute_zl_{zlmin:2.2f}_{zlmax:2.2f}/pzl_{args.logMmin}_{args.logMmax}.dat'
    if not os.path.exists(fpath):
        print('CRITICAL: Please run precompute first.')
        sys.exit(1)

    zlbins, pzl, mean_redshift = np.loadtxt(fpath, unpack=True)
    func = interp1d(np.cumsum(pzl), zlbins)
    median_lzred = func(0.5)

    # Initialize model
    mm = model(H0, Om0, lenstype, args.logMmin, args.logMmax, zlmin, zlmax, Njacks, zdiff)

    # Covariance Inversion & Hartlap factor
    icov = np.linalg.inv(cov)
    hartlap_factor = (Njacks - len(data) - 2) * 1.0 / (Njacks - 1)
    icov = hartlap_factor * icov
        
    print('here here')
    print(rbins, data, icov)

    # Setup Walkers and Dimensions
    nwalkers = 64 #if 'fixed' in args.model_type else 32
    
    np.random.seed(args.seed)
    p_alpha = np.random.uniform(0.9, 1.1, nwalkers) 
    p_logmh = np.log10(np.random.uniform(10**args.logMmin * 1e2, 10**args.logMmax * 1e2, nwalkers))
    p_conc  = np.random.uniform(0.1, 10, nwalkers)

    if args.model_type == 'nfw_fixed':
        ndim = 2
        p_0 = np.transpose([p_alpha, p_logmh])
    elif args.model_type == 'nfw_free':
        ndim = 3
        p_0 = np.transpose([p_alpha, p_logmh, p_conc])

    # Sampler Initialization (Notice Re_Mpc added to args)
    sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, pool=pool, 
                                    args=[rbins, data, icov, mm, median_lzred, args.model_type, Re_Mpc])

    outputdir = 'output_mcmc_desi_runs' 
    os.makedirs(outputdir, exist_ok=True)
    
    # --- DYNAMIC FILENAME TAGGING ---
    file_tag = f"{args.model_type}_lmstelmin_{args.logMmin:2.2f}_lmstelmax_{args.logMmax:2.2f}_seed_{args.seed}_" + args.mockdir.split('/')[-2]
    if args.sigma_Roff != -999:
        file_tag += f"_sigma_off_{args.sigma_Roff:2.2f}"
    if args.sigma_logre > 0.0:
        file_tag += f"_sigRe_{args.sigma_logre:2.2f}"
        
    burnfile = f'./{outputdir}/burnfile_{file_tag}.dat'
    burnpred = f'./{outputdir}/burnpredfile_{file_tag}.dat'
    chainfile = f'./{outputdir}/chainfile_{file_tag}.dat'
    predfile = f'./{outputdir}/predfile_{file_tag}.dat'

    print("Running burn-in (2000 steps)...")
    pos = runchain(2000, sampler, burnfile, burnpred, p_0, nwalkers)
    sampler.reset()

    print("Running production (4000 steps)...")
    pos = runchain(2000, sampler, chainfile, predfile, pos, nwalkers)
    
    print(f"Execution completed for {args.logMmin} - {args.logMmax}")
    pool.close()
